### ISSUE TITLE
License Verification inside javascript without php

### ISSUE THREAD

**Issue by abdullahilashik** [Freemius/freemius-checkout-js#11]
Hi, can you help me with the guide how can i verify license from inside my js code without the help of backend php scripts?

**Comment by swashata** [comment]
Hello,

Could you please explain your use case a bit more? From what I understand, you want to verify the license. For that, you need to hit an API endpoint for which you need a backend.

**Comment by abdullahilashik** [comment]
This issue was resolved. with the new LiteSDK the requirement satisfies.
